const mapping = {
    "pl_name": "Planet Name",
    "hostname": "Host Name",
    "default_flag": "Default Parameter Set",
    "sy_snum": "Number of Stars",
    "sy_pnum": "Number of Planets",
    "discoverymethod": "Discovery Method",
    "disc_year": "Discovery Year",
    "disc_facility": "Discovery Facility",
    "soltype": "Solution Type",
    "pl_controv_flag": "Controversial Flag",
    "pl_refname": "Planetary Parameter Reference",
    "pl_orbper": "Orbital Period [days]",
    "pl_orbsmax": "Orbit Semi-Major Axis [au])",
    "pl_rade": "Planet Radius [Earth Radius]",
    "pl_radj": "Planet Radius [Jupiter Radius]",
    "pl_msinie": "Planet Mass*sin(i) [Earth Mass]",
    "pl_msinij": "Planet Mass*sin(i) [Jupiter Mass]",
    "pl_bmassprov": "Planet Mass or Mass*sin(i) Provenance",
    "pl_orbeccen": "Eccentricity",
    "pl_insol": "Insolation Flux [Earth Flux]",
    "pl_eqt": "Equilibrium Temperature [K]",
    "ttv_flag": "Data show Transit Timing Variations",
    "st_refname": "Stellar Parameter Reference",
    "st_spectype": "Spectral Type",
    "st_teff": "Stellar Effective Temperature [K]",
    "st_rad": "Stellar Radius [Solar Radius]",
    "st_mass": "Stellar Mass [Solar mass]",
    "st_met": "Stellar Metallicity [dex]",
    "st_metratio": "Stellar Metallicity Ratio",
    "st_logg": "Stellar Surface Gravity [log10(cm/s**2)]",
    "sy_refname": "System Parameter Reference",
    "rastr": "RA [sexagesimal]",
    "decstr": "Dec [sexagesimal]",
    "sy_dist": "Distance [pc]",
    "sy_vmag": "V (Johnson) Magnitude",
    "sy_kmag": "Ks (2MASS) Magnitude",
    "sy_gaiamag": "Gaia Magnitude",
    "rowupdate": "Date of Last Update",
    "pl_pubdate": "Planetary Parameter Reference Publication Date",
    "releasedate": "Release Date"
};


const inputsRangeList = [
    "sy_num",
    "sy_pum",
    "disc_year",
    "pl_orbper",
    "pl_orbsmax",
    "pl_rade",
    "pl_radj",
    "pl_msinie",
    "pl_msinij",
    "pl_orbeccen",
    "pl_insol",
    "pl_eqt",
    "st_teff",
    "st_rad",
    "st_mass",
    "st_met",
    "st_logg",
    "sy_dist",
    "sy_vmag",
    "sy_kmag",
    "sy_gaiamag"
];


export {mapping, inputsRangeList}